repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages:
          - commit
          - merge-commit
        language: system
        types: [python]
        entry: black
